version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8090:80
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
