"""Historia de certificates

Revision ID: d371a25b6812
Revises:
Create Date: 2023-06-17 17:58:56.022798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d371a25b6812"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("certified", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "certified")
    # ### end Alembic commands ###
