name: Docker Hub Upload Workflow
on:
  workflow_run:
    workflows: [Python CI]
    types: [completed]
  workflow_dispatch:

jobs:
  push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fiufit-users:latest
          
  deploy:
    runs-on: ubuntu-latest
    needs: push-docker-image
    steps:      
      - name: checkout
        uses: actions/checkout@master
      
      - uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: franco-jyq
     
      - name: Rollout deployment
        run: |
          kubectl config use-context https://cloud.okteto.com/
          kubectl rollout restart deployment/service-users --namespace=franco-jyq
